- name: vars from prompt
  hosts: localhost
  vars_prompt:
  - name: username
    prompt: please enter username
    private: false
  - name: password
    prompt: please enter the password
    private: true
  tasks:
  - name: vars from prompt
    ansible.builtin.debug:
     msg: "my username is {{ username }} and password is {{ password }}"