- name: variables from inventory file
  hosts: localhost
  tasks:
  - name: print from the inventory file
    vars:
     timings: "7:15 AM IST"
    ansible.builtin.debug:
     msg: "I am learning {{ course }} from trainer {{ trainer }} of duration {{ duration }} and timings are {{ timings }}"
