- name: Data Types
  hosts: localhost
  vars:
   course: DevOps   #(string)
   Tools:           #(list)
   - Linux
   - Ansible
   - Shell
   Experience:      #(map/dictionary)
    Devops: 3       #(number)
    Shell: 2
    TEraform: 1
   RealProject: true #(boolean)
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: "Course is :- {{ course }}; Tools are :- {{ Tools }}; Experience is :- {{ Experience }}; is RealProject :- {{ RealProject }} "
