- name: default
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "Hello {{ COURSE | default('Ansible')}}"

- name: upper case
  hosts: localhost
  vars:
   wishes: "hello good morning"
  tasks:
  - name: convert to upper case
    ansible.builtin.debug:
     msg: " {{ wishes | upper }}"

- name: lower case
  hosts: localhost
  vars:
   wishes: "Hello GOOD MOrning"
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
     msg: " {{ wishes | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
  - numbers: [1, 2, 3, 3, 4, 4, 5, 6, 6]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
     msg: " {{ numbers | unique }}"

- name: min and max value
  hosts: localhost
  vars:
  - numbers: [1, 2, 3, 3, 4, 4, 5, 6, 6]
  tasks:
  - name: print min and max value
    ansible.builtin.debug:
     msg: " min is : {{ numbers | min }}, max is : {{ numbers | max }}"

- name: convert dictionary to items/lists
  hosts: localhost
  vars:
   my_dict:
    course: DevOps
    trainer: siva
    duration: 120hrs 
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  
  - name: after convert
    ansible.builtin.debug:
     msg: "After convert:  {{ my_dict | dict2items }}"



- name: convert dictionary to items/lists
  hosts: localhost
  vars:
   my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'} 
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  
  - name: after convert
    ansible.builtin.debug:
     msg: "After convert:  {{ my_list | items2dict }}"
