- name: install packages using loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages 
    ansible.builtin.dnf:
     name: "{{ item }}"
     state: latest
    loop:
    - nginx
    - mysql
    - postfix